jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Check out repository
          uses: actions/checkout@v2
        # ... other steps ...
        - name: Run Application
          run: npm start
          env:
            MONGODB_URL: ${{ secrets.MONGODB_URL }}
  