name: setting a github secret variable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Check out repository
          uses: actions/checkout@v2
        # ... other steps ...
        - name: Run Application
          run: npm start
          env:
            MONGODB_URL: ${{ secrets.MONGODB_URL }}
  